# Generated by Django 4.2.7 on 2023-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pin',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
