# Generated by Django 4.2.7 on 2023-11-25 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='price',
        ),
        migrations.RemoveField(
            model_name='content',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
