# Generated by Django 4.2.7 on 2023-11-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pin',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
