apiVersion: apps/v1
kind: Deployment
metadata:
  name: textshare-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: textshare-api
  template:
    metadata:
      labels:
        app: textshare-api
    spec:
      containers:
      - name: textshare-api-container
        image: mgdockerid/textshare:45388446ce0dcc662822e0aa09e19df03f779e76
        ports:
        - containerPort: 8000