apiVersion: apps/v1
kind: Deployment
metadata:
  name: textshare-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textshare-api
  template:
    metadata:
      labels:
        app: textshare-api
    spec:
      containers:
      - name: textshare
        image: mgdockerid/textshare:6fab02bbd19ec7e90c586df756f22e4db29f99a4
        ports:
        - containerPort: 8000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials  # The name of the Secret
                key: POSTGRES_USER   # The key in the Secret for the username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-credentials  # The name of the Secret
                key: POSTGRES_PASSWORD   # The key in the Secret for the password
          - name: DB_NAME
            #TODO read it in a configmap later
            value: textsharedb
          - name: DB_HOST
            value: postgres-textshare-svc  # PostgreSQL ClusterIP service name
